---
- name: install web components
  apt: name={{item}} state=present
  tags: ['packages']
  with_items:
    - apache2
    - libapache2-mod-wsgi-py3

- name: ensure mod_wsgi is enabled
  apache2_module: name=wsgi state=present
  tags: ['configure']
  notify: restart apache2

- name: de-activate default apache site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  tags: ['configure']
  notify: restart apache2

- name: ensure apache2 is running
  service: name=apache2 state=started enabled=yes
  tags: ['service']
